### ISSUE TITLE
Unable to create Session using the API and following instructions in docs

### ISSUE THREAD

**Issue by perlDreamer** [plainblack/ving#173]
Docs say to use apiKey and privateKey:

https://plainblack.github.io/ving/rest/Session.html

If you pass those, then you get this error:

```
"content" : "{\"url\":\"/api/v1/session\",\"statusCode\":441,\"statusMessage\":\"Missing Required Parameter\",\"message\":\"apiSecret is required.\",\"stack\":\"<pre><span class=\\\"stack internal\\\">at createError (./node_modules/h3/dist/index.mjs:79:15)</span>\\n<span class=\\\"stack\\\">at ouch (./ving/utils/ouch.mjs:47:12)</span>\\n<span class=\\\"stack\\\">at testRequired (./ving/utils/rest.mjs:130:19)</span>\\n<span class=\\\"stack\\\">at Object.handler (./server/api/v1/session/index.post.mjs:25:5)</span>\\n<span class=\\\"stack internal\\\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\\n<span class=\\\"stack internal\\\">at async ./node_modules/h3/dist/index.mjs:1962:19</span>\\n<span class=\\\"stack internal\\\">at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)</span>\\n<span class=\\\"stack internal\\\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)</span></pre>\",\"data\":\"apiSecret\"}",
```

**Comment by perlDreamer** [comment]
API Key screen also suggests API Key and Private Key

<img width="1449" alt="Screenshot 2024-06-27 at 4 15 01 PM" src="https://github.com/plainblack/ving/assets/48078/46c123d2-cfc4-4be8-8460-2ff61bec93cc">

**Comment by rizen** [comment]
fixed
